# @package _group_
name: svgp_regression
_target_: online_gp.models.OnlineSVGPRegression
init_ratio: 0.05
streaming: True
num_inducing: 256
lr: 1e-2
prior_beta: 1e-3
online_beta: 1e-3
learn_inducing_locations: True
num_update_steps: ${batch_size}