# @package _group_
name: walker2d_v2
type: regression
_target_: online_gp.datasets.regression.Walker2dV2
input_dim: 23
base_lr: 1e-2
dataset_dir: /datasets/mujoco/Walker2dV2
subsample_ratio: 1.0
split_seed: 0
shuffle: True